image: node:16

cache:
  paths:
    - node_modules/

before_script:
  - npm install

pages:
  stage: build
  script:
    - npm run build
    - cp -r build/* public/
  artifacts:
    paths:
      - public
  only:
    - main