image: node:20

cache: {}

before_script:
  - npm install --prefer-offline --no-audit

pages:
  stage: deploy
  script:
    - npm run build
    - rm -rf public
    # 创建正确的目录结构
    - mkdir -p public/zzu-china
    - mv build/* public/zzu-china/
    # 为 SPA 路由创建 404 重定向
    - cp public/zzu-china/index.html public/zzu-china/404.html
    # 创建根目录的重定向到 zzu-china
    - echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=/zzu-china/"></head><body>Redirecting...</body></html>' > public/index.html
    # 创建 _redirects 文件支持客户端路由
    - echo "/zzu-china/*    /zzu-china/index.html   200" > public/_redirects
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main



    