image: node:22.14.0

before_script:
  - npm install -g pnpm
  - pnpm install

create-pages:
  stage: build
  script:
    - pnpm run build
  artifacts:
    paths:
      - out
  pages:
    publish: out
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
 