image: node:18

# Define the stages used in this pipeline
stage: 
    - build
    - deploy

# Build the React App

build:
  stage: build  
  script:
    - npm install
    - npm run build
    - mv dist public
  artifacts:
    paths:
      - public


# Deploy to GitLab Pages
pages:
  stage: deploy
  script:
    - echo "Deployed successfullly"
  artifacts:
    paths:
      - public
    only:
      - main
  
