image: node:20

cache: {}

before_script:
  - npm install --prefer-offline --no-audit

pages:
  stage: deploy
  script:
    - npm run build
    - rm -rf public
    - mkdir -p public
    # 直接使用构建的文件
    - cp -r build/* public/
    # 为 SPA 路由创建 404 重定向
    - cp public/index.html public/404.html
    # 创建 _redirects 文件支持客户端路由
    - echo "/*    /index.html   200" > public/_redirects
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main