image: node:18.20.0

build:
  stage: build
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - .npm
  before_script:
    - npm ci
  script:
    - npm run build
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - .npm
  before_script:
    - npm ci
  script:
    - npm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH