// from the internet: https://www.pexels.com/ 为了减少文件的大小
// africa-tour-2


export const data = {
  africa: {
    description: 'Experience wild Africa: thrilling safaris, stunning landscapes, and unforgettable moments from savannas to waterfalls.',
    backImg: '/assets/europeBack.jpg',
    tours: [
      {
        title: 'Safari: Bush Camps',
        text: 'lorem20',
        style: 'active',
        service: 'basic',
        img: 'https://images.pexels.com/photos/3889918/pexels-photo-3889918.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'South Africa, Botswana',
        rating: 'Average',
        days: 9,
        type: 'Small group',
        price: 3200,
        date: 'June 01, 2025',
        age: '12+'
      },
      {
        title: 'Kenya Wildlife Expedition',
        text: 'Explore Kenya’s iconic wildlife and dramatic landscapes.',
        style: 'family',
        service: 'comfort',
        img: 'https://images.pexels.com/photos/34098/south-africa-hluhluwe-giraffes-pattern.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Kenya, Maasai Mara',
        rating: 'Average',
        days: 4,
        type: 'Family group',
        price: 2700,
        date: 'August 10, 2025',
        age: '8+'
      },
      {
        title: 'Kilimanjaro Ascent: Machame Route Adventure',
        text: 'Trek the scenic Machame route up Africa’s highest peak.',
        style: 'active',
        service: 'standard',
        img: '/assets/africa-tour-3.jpg',
        place: 'Tanzania, Kilimanjaro',
        rating: 'Demanding',
        days: 8,
        type: 'Small group',
        price: 2500,
        date: 'July 15, 2025',
        age: '16+'
      },
      {
        title: 'West African Adventure',
        text: 'Discover vibrant cultures and traditions in West Africa.',
        style: 'classic',
        service: 'basic',
        img: '/assets/africa-tour-4.jpg',
        place: 'Benin, Ghana, Togo',
        rating: 'Average',
        days: 8,
        type: 'Small group',
        price: 2500,
        date: 'July 15, 2025',
        age: '12+'
      },
      {
        title: 'Namibia Desert Escape',
        text: 'Roam through the towering dunes of Sossusvlei and spot desert wildlife.',
        style: 'active',
        service: 'standard',
        img: 'https://images.pexels.com/photos/1539696/pexels-photo-1539696.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Namibia',
        rating: 'Average',
        days: 7,
        type: 'Small group',
        price: 2900,
        date: 'September 05, 2025',
        age: '12+'
      },
      {
        title: 'Morocco Sahara Caravan',
        text: 'Experience camel treks, kasbahs, and oasis towns in the Moroccan desert.',
        style: 'classic',
        service: 'basic',
        img: 'https://images.pexels.com/photos/1731660/pexels-photo-1731660.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Morocco',
        rating: 'Average',
        days: 6,
        type: 'Small group',
        price: 2300,
        date: 'October 10, 2025',
        age: '10+'
      },
      {
        title: 'Egyptian Treasures',
        text: 'Uncover the wonders of ancient Egypt from Cairo to Luxor.',
        style: 'classic',
        service: 'comfort',
        place: 'Egypt',
        rating: 'Demanding',
        days: 10,
        type: 'Small group',
        price: 3100,
        date: 'November 01, 2025',
        age: '10+'
      },
      {
        title: 'Madagascar Wildlife & Rainforest',
        text: 'Explore the unique flora and fauna of Madagascar’s eastern jungles.',
        style: 'active',
        service: 'standard',
        img: 'https://images.pexels.com/photos/14181536/pexels-photo-14181536.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Madagascar',
        rating: 'Average',
        days: 9,
        type: 'Small group',
        price: 2800,
        date: 'December 03, 2025',
        age: '14+'
      },
      {
        title: 'Victoria Falls & Zambezi Adventure',
        text: 'Witness the majestic falls and raft the powerful Zambezi River.',
        style: 'active',
        service: 'basic',
        img: 'https://images.pexels.com/photos/27878404/pexels-photo-27878404.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: '  , Zambia',
        rating: 'Demanding',
        days: 5,
        type: 'Small group',
        price: 2600,
        date: 'December 20, 2025',
        age: '15+'
      }]
    },
    europe: {
    description: "Experience Europe’s rich history, world-famous cuisine, and breathtaking landscapes. From ancient cities to stunning coastlines, Europe offers a blend of culture, adventure, and charm.",
    backImg: '/assets/europeBack.jpg', 
    tours: [
      {
        title: 'Trekking Mont Blanc',
        text: 'Challenge yourself with alpine trails through France, Italy, and Switzerland.',
        style: 'active',
        service: 'standard',
        img: 'https://images.pexels.com/photos/1067109/pexels-photo-1067109.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Italy, France, Switzerland',
        rating: 'Demanding',
        days: 8,
        type: 'Small group',
        price: 3400,
        date: 'June 01, 2025',
        age: '14+'
      },
      {
        title: 'Best of Iceland',
        text: 'See waterfalls, glaciers, geysers, and the Northern Lights on a breathtaking loop.',
        style: 'classic',
        service: 'comfort',
        img: '/assets/europe-tour-2.jpg',
        place: 'Iceland',
        rating: 'Demanding',
        days: 8,
        type: 'Small group',
        price: 2500,
        date: 'July 15, 2025',
        age: '12+'
      },
      {
        title: 'Finnish Lapland Discovery',
        text: 'Meet reindeer, enjoy arctic landscapes, and experience the magic of the north.',
        style: 'family',
        service: 'comfort',
        img: 'https://images.pexels.com/photos/3307194/pexels-photo-3307194.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Finland',
        rating: 'Average',
        days: 8,
        type: 'Family group',
        price: 2700,
        date: 'August 10, 2025',
        age: '6+'
      },
      {
        title: 'Highlights of Poland',
        text: 'Dive into Poland’s history, charming cities, and natural wonders.',
        style: 'classic',
        service: 'basic',
        img: 'https://images.pexels.com/photos/15597194/pexels-photo-15597194.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Poland',
        rating: 'Average',
        days: 8,
        type: 'Family group',
        price: 2700,
        date: 'August 10, 2025',
        age: '10+'
      },
      {
        title: 'Greek Island Hopper',
        text: 'Hop from Santorini to Mykonos, soaking in beaches, sunsets, and history.',
        style: 'classic',
        service: 'comfort',
        img: 'https://images.pexels.com/photos/3264723/pexels-photo-3264723.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Greece',
        rating: 'Demanding',
        days: 7,
        type: 'Small group',
        price: 2900,
        date: 'July 01, 2025',
        age: '12+'
      },
      {
        title: 'Norwegian Fjords Explorer',
        text: 'Cruise and hike through Norway’s epic fjord landscapes.',
        style: 'active',
        service: 'standard',
        img: 'https://images.pexels.com/photos/11660966/pexels-photo-11660966.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Norway',
        rating: 'Demanding',
        days: 9,
        type: 'Small group',
        price: 3200,
        date: 'August 15, 2025',
        age: '14+'
      },
      {
        title: 'Spain and Portugal Discovery',
        text: 'Uncover Iberian culture, cuisine, and architecture from Madrid to Lisbon.',
        style: 'classic',
        service: 'comfort',
        img: 'https://images.pexels.com/photos/705423/pexels-photo-705423.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Spain, Portugal',
        rating: 'Average',
        days: 10,
        type: 'Small group',
        price: 3100,
        date: 'September 10, 2025',
        age: '10+'
      },
      {
        title: 'Alpine Family Adventure',
        text: 'A perfect blend of mountain fun and cultural stops for families.',
        style: 'family',
        service: 'comfort',
        img: 'https://images.pexels.com/photos/27857644/pexels-photo-27857644.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Austria, Germany',
        rating: 'Average',
        days: 7,
        type: 'Family group',
        price: 2800,
        date: 'June 20, 2025',
        age: '8+'
      },
      {
        title: 'Baltic Capitals Explorer',
        text: 'Stroll the cobbled streets of Tallinn, Riga, and Vilnius.',
        style: 'classic',
        service: 'basic',
        place: 'Estonia, Latvia, Lithuania',
        rating: 'Average',
        days: 6,
        type: 'Small group',
        price: 2400,
        date: 'May 25, 2025',
        age: '12+'
      },
      {
        title: 'Scotland Highlands Adventure',
        text: 'Hike glens, spot lochs, and explore castle ruins in Scotland.',
        style: 'active',
        service: 'standard',
        img: 'https://images.pexels.com/photos/2682675/pexels-photo-2682675.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Scotland',
        rating: 'Demanding',
        days: 8,
        type: 'Small group',
        price: 2900,
        date: 'August 25, 2025',
        age: '13+'
      }
    ]},
  asia: {
    description: "Discover Asia’s incredible diversity, from bustling metropolises to tranquil temples. Explore ancient traditions, exotic cuisine, and breathtaking natural wonders across this vast continent.",
    backImg: '/assets/asiaBack.jpg',

    tours: [
      {
        title: 'Japan Express – Osaka to Tokyo',
        text: 'Zoom between vibrant cities, temples, and traditions on this fast-paced Japan tour.',
        style: 'classic',
        service: 'comfort',
        img: 'https://images.pexels.com/photos/3583201/pexels-photo-3583201.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Japan',
        rating: 'Demanding',
        days: 8,
        type: 'Small group',
        price: 3000,
        date: 'June 01, 2025',
        age: '12+'
      },
      {
        title: 'Essential Tibet',
        text: 'Experience the spirituality and heights of Tibet with visits to monasteries and markets.',
        style: 'active',
        service: 'basic',
        img: '/assets/asia-tour-2.jpg',
        place: 'China, Nepal, Tibet',
        rating: 'Average',
        days: 8,
        type: 'Small group',
        price: 2500,
        date: 'July 15, 2025',
        age: '14+'
      },
      {
        title: 'Ancient China',
        text: 'Discover the Great Wall, Forbidden City, and more in this family-friendly tour.',
        style: 'family',
        service: 'comfort',
        img: 'https://images.pexels.com/photos/2412603/pexels-photo-2412603.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'China',
        rating: 'Average',
        days: 8,
        type: 'Family group',
        price: 2700,
        date: 'August 10, 2025',
        age: '6+'
      },
      {
        title: 'Bangkok to Singapore: Island Nights',
        text: 'From buzzing cities to serene islands, explore Southeast Asia’s nature and nightlife.',
        style: 'family',
        service: 'comfort',
        img: 'https://images.pexels.com/photos/1212956/pexels-photo-1212956.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Singapore, Malaysia, Thailand',
        rating: 'Average',
        days: 8,
        type: 'Family group',
        price: 2700,
        date: 'August 10, 2025',
        age: '10+'
      },
      {
        title: 'Mystic India Highlights',
        text: 'Explore palaces, temples, and bustling markets across northern India.',
        style: 'classic',
        service: 'basic',
        place: 'India',
        rating: 'Average',
        days: 9,
        type: 'Small group',
        price: 2600,
        date: 'September 01, 2025',
        age: '12+'
      },
      {
        title: 'Sri Lanka Coastal Discovery',
        text: 'Safari, temples, and tea plantations await on this lush island journey.',
        style: 'classic',
        service: 'comfort',
        img: 'https://images.pexels.com/photos/321582/pexels-photo-321582.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Sri Lanka',
        rating: 'Demanding',
        days: 7,
        type: 'Small group',
        price: 2500,
        date: 'July 05, 2025',
        age: '10+'
      },
      {
        title: 'Vietnam and Cambodia Explorer',
        text: 'From Halong Bay to Angkor Wat, discover Southeast Asia’s magic and heritage.',
        style: 'active',
        service: 'standard',
        img: 'https://images.pexels.com/photos/4652275/pexels-photo-4652275.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Vietnam, Cambodia',
        rating: 'Demanding',
        days: 10,
        type: 'Small group',
        price: 3100,
        date: 'October 01, 2025',
        age: '14+'
      },
      {
        title: 'Bali Family Escape',
        text: 'Enjoy volcano hikes, monkey forests, and beach days in tropical Bali.',
        style: 'family',
        service: 'comfort',
        img: 'https://images.pexels.com/photos/2412720/pexels-photo-2412720.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Indonesia',
        rating: 'Average',
        days: 8,
        type: 'Family group',
        price: 2700,
        date: 'June 20, 2025',
        age: '8+'
      },
    ]},

  northAmerica: {
    description: 'Explore North America’s diverse landscapes, from vibrant cities to vast wilderness. Discover stunning national parks, cultural hotspots, and unforgettable outdoor adventures.',
    backImg: '/assets/nAmericaBack.jpg',
    tours: [
      {
        title: 'Grand Canyon & National Parks Adventure',
        text: 'Hike and camp across the American Southwest’s most stunning landscapes.',
        style: 'active',
        service: 'standard',
        img: 'https://images.pexels.com/photos/2542340/pexels-photo-2542340.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'USA',
        rating: 'Demanding',
        days: 8,
        type: 'Small group',
        price: 3000,
        date: 'April 18, 2025',
        age: '12+'
      },
      {
        title: 'Canadian Rockies Explorer',
        text: 'Marvel at glaciers, lakes, and peaks in Banff and Jasper National Parks.',
        style: 'active',
        service: 'comfort',
        img: 'https://images.pexels.com/photos/30953093/pexels-photo-30953093.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Canada',
        rating: 'Demanding',
        days: 7,
        type: 'Small group',
        price: 3200,
        date: 'July 22, 2025',
        age: '10+'
      },
      {
        title: 'New Orleans & Southern Culture',
        text: 'Dive into jazz, cuisine, and history across the American South.',
        style: 'classic',
        service: 'standard',
        place: 'USA',
        rating: 'Average',
        days: 6,
        type: 'Family group',
        price: 2600,
        date: 'October 03, 2025',
        age: '8+'
      },
      {
        title: 'Mexico’s Ancient & Colonial Wonders',
        text: 'Explore Aztec ruins, colonial towns, and vibrant markets from Mexico City to Oaxaca.',
        style: 'classic',
        service: 'comfort',
        img: 'https://images.pexels.com/photos/3290068/pexels-photo-3290068.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Mexico',
        rating: 'Average',
        days: 9,
        type: 'Small group',
        price: 2800,
        date: 'August 12, 2025',
        age: '10+'
      },
      {
      title: 'Alaskan Wilderness Cruise',
      text: 'Sail through icy fjords, spot whales, and explore the rugged Alaskan frontier.',
      style: 'classic',
      service: 'comfort',
      img: '/assets/na-tour-5.jpg',
      place: 'USA (Alaska)',
      rating: 'Light',
      days: 10,
      type: 'Small group',
      price: 3900,
      date: 'June 10, 2025',
      age: '10+'
    },
    {
      title: 'New York City Highlights',
      text: 'Experience the iconic sights, culture, and food of the Big Apple.',
      style: 'classic',
      service: 'comfort',
      img: 'https://images.pexels.com/photos/64271/queen-of-liberty-statue-of-liberty-new-york-liberty-statue-64271.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      place: 'USA',
      rating: 'Easy',
      days: 5,
      type: 'Day tours',
      price: 2100,
      date: 'April 02, 2025',
      age: '8+'
    },

    {
      title: 'Route 66 American Roadtrip',
      text: 'Follow the legendary Route 66 across the heart of the USA.',
      style: 'classic',
      service: 'standard',
      img: 'https://images.pexels.com/photos/29559234/pexels-photo-29559234/free-photo-of-route-66.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      place: 'USA',
      rating: 'Average',
      days: 12,
      type: 'Small group',
      price: 3700,
      date: 'September 14, 2025',
      age: '14+'
    },
    
    ]},

  southAmerica: {
    description: 'Immerse yourself in South America’s vibrant cultures, lush rainforests, and spectacular mountain ranges. Experience colorful festivals, ancient ruins, and the warmth of its people.',
    backImg: '/assets/sAmericaBack.jpg',
    tours: [
      {
        title: 'Machu Picchu & Sacred Valley',
        text: 'Journey through Peru’s Incan heritage with breathtaking hikes and historic ruins.',
        style: 'active',
        service: 'comfort',
        img: 'https://images.pexels.com/photos/2516418/pexels-photo-2516418.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Peru',
        rating: 'Demanding',
        days: 8,
        type: 'Small group',
        price: 2800,
        date: 'May 20, 2025',
        age: '12+'
      },
      {
        title: 'Amazon Rainforest Expedition',
        text: 'Explore the lush biodiversity of the Amazon with expert naturalists and local guides.',
        style: 'active',
        service: 'standard',
        img: 'https://images.pexels.com/photos/1684885/pexels-photo-1684885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Brazil',
        rating: 'Challenging',
        days: 7,
        type: 'Family group',
        price: 2500,
        date: 'June 15, 2025',
        age: '10+'
      },
      {
        title: 'Patagonian Glaciers & Mountains',
        text: 'Adventure through the dramatic landscapes of southern Argentina and Chile.',
        style: 'active',
        service: 'comfort',
        img: 'https://images.pexels.com/photos/3428177/pexels-photo-3428177.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Argentina & Chile',
        rating: 'Demanding',
        days: 10,
        type: 'Small group',
        price: 3400,
        date: 'November 01, 2025',
        age: '14+'
      },
      {
        title: 'Colors of Colombia',
        text: 'Immerse yourself in Colombia’s vibrant cities, coffee region, and Caribbean coast.',
        style: 'classic',
        service: 'comfort',
        img: 'https://images.pexels.com/photos/13360140/pexels-photo-13360140.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        place: 'Colombia',
        rating: 'Average',
        days: 9,
        type: 'Small group',
        price: 2700,
        date: 'September 10, 2025',
        age: '10+'
      },
      {
  title: 'Rio Carnival & City Explorer',
  text: 'Experience the electric atmosphere of Rio during its world-famous carnival.',
  style: 'classic',
  service: 'comfort',
  place: 'Brazil',
  rating: 'Average',
  days: 6,
  type: 'Family group',
  price: 2500,
  date: 'February 28, 2025',
  age: '10+'
},
{
  title: 'Bolivian Salt Flats & Highlands',
  text: 'Photograph the surreal Uyuni salt flats and explore Andean villages.',
  style: 'active',
  service: 'standard',
  img: 'https://images.pexels.com/photos/3250360/pexels-photo-3250360.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  place: 'Bolivia',
  rating: 'Challenging',
  days: 7,
  type: 'Small group',
  price: 2600,
  date: 'August 21, 2025',
  age: '14+'
},
{
  title: 'Buenos Aires & Tango Nights',
  text: 'Dive into Argentine culture with dance, cuisine, and cosmopolitan flair.',
  style: 'classic',
  service: 'comfort',
  img: 'https://images.pexels.com/photos/31414149/pexels-photo-31414149.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  place: 'Argentina',
  rating: 'Easy',
  days: 5,
  type: 'Day tours',
  price: 2300,
  date: 'March 16, 2025',
  age: '10+'
},
{
  title: 'Andes to Amazon Trek',
  text: 'Combine mountain trails and rainforest excursions on this diverse journey.',
  style: 'active',
  service: 'standard',
  img: 'https://images.pexels.com/photos/931007/pexels-photo-931007.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  place: 'Peru & Ecuador',
  rating: 'Demanding',
  days: 10,
  type: 'Small group',
  price: 3600,
  date: 'May 12, 2025',
  age: '14+'
},]},

oceania: {
  description: 'Discover Oceania’s pristine beaches, rich indigenous cultures, and unforgettable natural wonders. From Australia’s outback to New Zealand’s fjords and the South Pacific’s idyllic islands, it’s a paradise for nature and adventure lovers.',
  backImg: '/assets/oceaniaBack.jpg',
  tours: [
    {
      title: 'Great Barrier Reef Adventure',
      text: 'Snorkel or dive among colorful corals and marine life off the coast of Queensland.',
      style: 'active',
      service: 'comfort',
      img: '/assets/oc-tour-1.jpg',
      place: 'Australia',
      rating: 'Light',
      days: 6,
      type: 'Small group',
      price: 3200,
      date: 'April 10, 2025',
      age: '10+'
    },
    {
      title: 'New Zealand South Island Explorer',
      text: 'Hike through fjords, mountains, and lakes in breathtaking natural surroundings.',
      style: 'active',
      service: 'comfort',
      img: '/assets/oc-tour-2.jpg',
      place: 'New Zealand',
      rating: 'Demanding',
      days: 10,
      type: 'Small group',
      price: 3900,
      date: 'November 15, 2025',
      age: '12+'
    },
    {
      title: 'Sydney & Coastal Highlights',
      text: 'Discover Sydney’s icons, beaches, and nearby national parks in a relaxed tour.',
      style: 'classic',
      service: 'standard',
      img: '/assets/oc-tour-3.jpg',
      place: 'Australia',
      rating: 'Easy',
      days: 5,
      type: 'Independent travel',
      price: 2500,
      date: 'May 05, 2025',
      age: '8+'
    },
    {
      title: 'Fiji Island Escape',
      text: 'Relax on white-sand beaches, snorkel in crystal-clear waters, and enjoy island hospitality.',
      style: 'classic',
      service: 'comfort',
      img: 'https://images.pexels.com/photos/32279568/pexels-photo-32279568.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      place: 'Fiji',
      rating: 'Easy',
      days: 7,
      type: 'Family group',
      price: 3300,
      date: 'June 18, 2025',
      age: '6+'
    },
    {
      title: 'Tasmania Wilderness & Wine',
      text: 'Hike through remote national parks and taste local wines and gourmet produce.',
      style: 'active',
      service: 'comfort',
      place: 'Australia (Tasmania)',
      rating: 'Average',
      days: 8,
      type: 'Small group',
      price: 3100,
      date: 'March 22, 2025',
      age: '12+'
    },
    {
      title: 'Outback & Uluru Experience',
      text: 'Journey deep into the red center and learn about Aboriginal heritage.',
      style: 'active',
      service: 'standard',
      img: '/assets/oc-tour-8.jpg',
      place: 'Australia',
      rating: 'Average',
      days: 6,
      type: 'Small group',
      price: 2700,
      date: 'September 12, 2025',
      age: '10+'
    },
    {
      title: 'Vanuatu Volcano & Village Life',
      text: 'Explore active volcanoes and stay in traditional villages for an immersive trip.',
      style: 'active',
      service: 'standard',
      img: '/assets/oc-tour-9.jpg',
      place: 'Vanuatu',
      rating: 'Challenging',
      days: 7,
      type: 'Adventure group',
      price: 2900,
      date: 'August 03, 2025',
      age: '14+'
    },
    {
      title: 'Bay of Islands Sailing Adventure',
      text: 'Sail around New Zealand’s stunning Northland region with daily excursions.',
      style: 'classic',
      service: 'comfort',
      img: 'https://images.pexels.com/photos/26631274/pexels-photo-26631274.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      place: 'New Zealand',
      rating: 'Light',
      days: 5,
      type: 'Small group',
      price: 2700,
      date: 'December 05, 2025',
      age: '10+'
    }
  ]
}

};
